### ISSUE TITLE
[ENHANCEMENT] 

### ISSUE THREAD

**Issue by UvuvDev** [jazonshou/Graphy#6]
Better documentation I think is necessary. Maybe using Github's built in Wiki tab? What do you think @jazonshou

**Comment by jazonshou** [comment]
I'm not a huge fan of Github wiki. Is it alright if you could just expand the documentation on the ReadMe? Otherwise, I'm open to publishing a simple website with Github pages

**Comment by UvuvDev** [comment]
Alright, I'll update the ReadMe soon then.
